apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.39.0/release.yaml

patches:
- patch: |-
    - op: replace
      path: /apiVersion
      value: autoscaling/v2beta2
  target:
    group: autoscaling
    version: v2beta1
    kind: HorizontalPodAutoscaler
- path: ./horizontal-pod-autoscaler.patch.yaml
  target:
    group: autoscaling
    version: v2beta2
    kind: HorizontalPodAutoscaler
