---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-ci
  namespace: my-ci
spec:
  interval: 1m
  targetNamespace: my-ci
  sourceRef:
    kind: GitRepository
    name: my-ci
  path: ./ci
  prune: true
  wait: true
