---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-ci
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/base/my-ci
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

